schema_version: "1.0"
config_type: exchanges
exchanges:
  NVDA: Nasdaq
  AMD: Nasdaq
  INTC: Nasdaq
  AVGO: Nasdaq
  MRVL: Nasdaq
  QCOM: Nasdaq
  ARM: Nasdaq
  MU: Nasdaq
  SMCI: Nasdaq
  ALAB: Nasdaq
  CRDO: Nasdaq
  LSCC: Nasdaq
  MPWR: Nasdaq
  AMBA: Nasdaq
  RMBS: Nasdaq
  TXN: Nasdaq
  ADI: Nasdaq
  MCHP: Nasdaq
  NXPI: Nasdaq
  "ON": NASDAQ
  SWKS: Nasdaq
  QRVO: Nasdaq
  POWI: Nasdaq
  DIOD: Nasdaq
  ALGM: Nasdaq
  SLAB: Nasdaq
  SITM: Nasdaq
  CAMT: Nasdaq
  AMAT: Nasdaq
  LRCX: Nasdaq
  KLAC: Nasdaq
  ONTO: NYSE
  ACLS: Nasdaq
  UCTT: Nasdaq
  ICHR: Nasdaq
  FORM: Nasdaq
  AEIS: Nasdaq
  VECO: Nasdaq
  KLIC: Nasdaq
  COHU: Nasdaq
  ASML: Nasdaq
  NVMI: Nasdaq
  COHR: NYSE
  LITE: Nasdaq
  FN: NYSE
  AAOI: Nasdaq
  POET: Nasdaq
  CIEN: NYSE
  ANET: NYSE
  ADTN: Nasdaq
  HLIT: Nasdaq
  DZSI: US
  CALX: NYSE
  EXTR: Nasdaq
  VRT: NYSE
  MOD: NYSE
  NVT: NYSE
  ETN: NYSE
  PWR: NYSE
  HUBB: NYSE
  AAON: Nasdaq
  JCI: NYSE
  TT: NYSE
  LII: NYSE
  CARR: NYSE
  GNRC: NYSE
  BE: NYSE
  PLTR: Nasdaq
  SNOW: NYSE
  DDOG: Nasdaq
  MDB: Nasdaq
  NOW: NYSE
  CRM: NYSE
  AI: NYSE
  PATH: NYSE
  TEM: Nasdaq
  APP: Nasdaq
  ESTC: NYSE
  CFLT: Nasdaq
  GTLB: Nasdaq
  RGTI: Nasdaq
  IONQ: NYSE
  QBTS: Nasdaq
  QUBT: Nasdaq
  ARQQ: Nasdaq
  LAES: Nasdaq
  BBAI: NYSE
  SOUN: Nasdaq
  INOD: Nasdaq
  SERV: Nasdaq
  KSCP: Nasdaq
  NNDM: Nasdaq
  MSFT: Nasdaq
  AMZN: Nasdaq
  GOOGL: Nasdaq
  META: Nasdaq
  AAPL: Nasdaq
  ORCL: NYSE
  ADBE: Nasdaq
  IBM: NYSE
  SAP: NYSE
  NFLX: Nasdaq
  INTU: Nasdaq
  CSCO: Nasdaq
