METRIC_METADATA = {
    "portfolio_value": {
        "key": "portfolio_value",
        "display_name": "Portfolio value",
        "plain_description": "Current cash plus the market value of all covered holdings.",
        "unit": "currency",
        "direction": "contextual",
        "tier": "simple",
    },
    "net_contributed_capital": {
        "key": "net_contributed_capital",
        "display_name": "Net contributed capital",
        "plain_description": "Opening capital and deposits minus withdrawals.",
        "unit": "currency",
        "direction": "contextual",
        "tier": "simple",
    },
    "total_gain_loss": {
        "key": "total_gain_loss",
        "display_name": "Total gain or loss",
        "plain_description": "Portfolio value minus net contributed capital.",
        "unit": "currency",
        "direction": "higher_is_better",
        "tier": "simple",
    },
    "cash_available": {
        "key": "cash_available",
        "display_name": "Cash available",
        "plain_description": "Ledger cash not currently invested in holdings.",
        "unit": "currency",
        "direction": "contextual",
        "tier": "simple",
    },
    "stocks_value": {
        "key": "stocks_value",
        "display_name": "Stocks value",
        "plain_description": "Current market value of covered stock positions.",
        "unit": "currency",
        "direction": "contextual",
        "tier": "simple",
    },
    "position_weight": {
        "key": "position_weight",
        "display_name": "Position weight",
        "plain_description": "Share of total portfolio value held in this security.",
        "unit": "percentage",
        "direction": "contextual",
        "tier": "simple",
    },
    "latest_price": {
        "key": "latest_price",
        "display_name": "Latest price",
        "plain_description": "Most recent covered closing price known by the as-of date.",
        "unit": "currency",
        "direction": "contextual",
        "tier": "simple",
    },
    "opportunity_score": {
        "key": "opportunity_score",
        "display_name": "Opportunity Score",
        "plain_description": "Peer-relative 0-100 percentile of six thesis legs; not an absolute quality score or return forecast.",
        "unit": "score_0_100",
        "direction": "higher_is_better",
        "tier": "simple",
    },
    "target_weight": {
        "key": "target_weight",
        "display_name": "Target weight",
        "plain_description": "Maximum portfolio share selected by deterministic risk policy.",
        "unit": "percentage",
        "direction": "contextual",
        "tier": "simple",
    },
    "suggested_amount": {
        "key": "suggested_amount",
        "display_name": "Suggested amount",
        "plain_description": "Policy-sized amount to deploy or raise; Auspex never executes it.",
        "unit": "currency",
        "direction": "contextual",
        "tier": "simple",
    },
    "estimated_cost": {
        "key": "estimated_cost",
        "display_name": "Estimated cost",
        "plain_description": "Estimated brokerage, spread, and applicable Swiss stamp duty.",
        "unit": "currency",
        "direction": "lower_is_better",
        "tier": "simple",
    },
    "confidence": {
        "key": "confidence",
        "display_name": "Confidence",
        "plain_description": "Data-coverage confidence, not certainty about future performance.",
        "unit": "category",
        "direction": "higher_is_better",
        "tier": "simple",
    },
    "position_quantity": {
        "key": "position_quantity",
        "display_name": "Position quantity",
        "plain_description": "Current number of shares derived from the effective ledger.",
        "unit": "shares",
        "direction": "contextual",
        "tier": "simple",
    },
    "transaction_count": {
        "key": "transaction_count",
        "display_name": "Ledger entries",
        "plain_description": "Immutable audit rows, including corrections and superseded originals.",
        "unit": "count",
        "direction": "contextual",
        "tier": "advanced",
    },
    "total_fees": {
        "key": "total_fees",
        "display_name": "Fees and commissions",
        "plain_description": "All recorded ledger costs to date.",
        "unit": "currency",
        "direction": "lower_is_better",
        "tier": "simple",
    },
    "dividends": {
        "key": "dividends",
        "display_name": "Dividends",
        "plain_description": "Gross dividends recorded before separate fees.",
        "unit": "currency",
        "direction": "higher_is_better",
        "tier": "simple",
    },
    "interest": {
        "key": "interest",
        "display_name": "Interest",
        "plain_description": "Gross interest income recorded in the ledger.",
        "unit": "currency",
        "direction": "higher_is_better",
        "tier": "simple",
    },
    "cash_impact": {
        "key": "cash_impact",
        "display_name": "Cash impact",
        "plain_description": "Server-derived signed cash movement for one ledger event.",
        "unit": "currency",
        "direction": "contextual",
        "tier": "advanced",
    },
    "fx_rate": {
        "key": "fx_rate",
        "display_name": "FX rate",
        "plain_description": "Recorded conversion rate: one transaction-currency unit in base currency.",
        "unit": "rate",
        "direction": "contextual",
        "tier": "advanced",
    },
    "monthly_outlook_range": {
        "key": "monthly_outlook_range",
        "display_name": "Monthly outlook range",
        "plain_description": "Uncertain one-month value range; published only when measured portfolio volatility is available.",
        "unit": "currency_range",
        "direction": "contextual",
        "tier": "advanced",
    },
    "thesis_linkage": {
        "key": "thesis_linkage",
        "display_name": "Thesis fit",
        "plain_description": "How strongly the security is linked to the selected investment theme.",
        "unit": "score_contribution",
        "direction": "higher_is_better",
        "tier": "advanced",
    },
    "attention_acceleration": {
        "key": "attention_acceleration",
        "display_name": "Rising attention",
        "plain_description": "Whether relevant market and information activity is accelerating.",
        "unit": "score_contribution",
        "direction": "higher_is_better",
        "tier": "advanced",
    },
    "smart_money": {
        "key": "smart_money",
        "display_name": "Smart-money activity",
        "plain_description": "Insider and institutional activity contributing to the score.",
        "unit": "score_contribution",
        "direction": "higher_is_better",
        "tier": "advanced",
    },
    "fundamental_health": {
        "key": "fundamental_health",
        "display_name": "Fundamental health",
        "plain_description": "Quality and valuation-supported business fundamentals.",
        "unit": "score_contribution",
        "direction": "higher_is_better",
        "tier": "advanced",
    },
    "valuation_brake": {
        "key": "valuation_brake",
        "display_name": "Valuation discipline",
        "plain_description": "Contribution that reduces enthusiasm when valuation looks stretched.",
        "unit": "score_contribution",
        "direction": "higher_is_better",
        "tier": "advanced",
    },
    "crowding_positioning": {
        "key": "crowding_positioning",
        "display_name": "Crowding position",
        "plain_description": "Whether the opportunity remains under-recognized or has become crowded.",
        "unit": "score_contribution",
        "direction": "higher_is_better",
        "tier": "advanced",
    },
}


def metric_metadata_payload() -> list[dict]:
    return [METRIC_METADATA[key] for key in sorted(METRIC_METADATA)]