"""Deterministic scoring engine — six legs, cohort normalisation, composite (arc42 §5.5).

Pure Python. No I/O, no LLM. Fully unit-testable.
"""

from __future__ import annotations

from auspex.scoring.composite import (
    CompositeResult,
    LegCompositeResult,
    LegCrossSection,
    LegDeltaDecomposition,
    classify_direction,
    compute_percentile,
    compute_security_composite,
    cross_sectional_zscores,
    decompose_leg_delta,
)
from auspex.scoring.coverage import applicable_legs, coverage, is_stale
from auspex.scoring.engine import (
    SecurityScoreResult,
    SecurityScoringInput,
    build_cohort_scopes,
    score_universe,
)
from auspex.scoring.legs import (
    AttentionEvent,
    FundamentalHealthInputs,
    FundamentalHealthResult,
    InsiderTxnEvent,
    NarrativeClaimEvent,
    ThemeClaimEvent,
    ValuationMetrics,
    attention_acceleration,
    enterprise_value,
    fcf_margin,
    fundamental_health,
    gross_margin_trend_slope,
    narrative_premium,
    net_cash_ratio,
    revenue_growth_yoy,
    roic,
    smart_money,
    thesis_linkage,
    valuation_brake,
)
from auspex.scoring.normalize import (
    COHORT_MIN_SIZE,
    PARENT_MIN_SIZE,
    CohortScope,
    assign_cohort_scope,
    blended_percentile_rank,
    blended_zscore,
    clip,
    exponential_decay,
    mean_std,
    percentile_rank,
    percentile_rank_fraction,
    shrinkage_lambda,
    shrinkage_tier_weights,
    winsorise,
    zscore,
)
from auspex.scoring.sessions import (
    contiguous_weakening_streak,
    latest_session_on_or_before,
    normalise_calendar,
    nth_prior_session,
    prior_sessions,
    sessions_between,
)

__all__ = [
    "CompositeResult",
    "LegCompositeResult",
    "LegCrossSection",
    "LegDeltaDecomposition",
    "classify_direction",
    "compute_percentile",
    "compute_security_composite",
    "cross_sectional_zscores",
    "decompose_leg_delta",
    "applicable_legs",
    "coverage",
    "is_stale",
    "SecurityScoreResult",
    "SecurityScoringInput",
    "build_cohort_scopes",
    "score_universe",
    "AttentionEvent",
    "FundamentalHealthInputs",
    "FundamentalHealthResult",
    "InsiderTxnEvent",
    "NarrativeClaimEvent",
    "ThemeClaimEvent",
    "ValuationMetrics",
    "attention_acceleration",
    "enterprise_value",
    "fcf_margin",
    "fundamental_health",
    "gross_margin_trend_slope",
    "narrative_premium",
    "net_cash_ratio",
    "revenue_growth_yoy",
    "roic",
    "smart_money",
    "thesis_linkage",
    "valuation_brake",
    "CohortScope",
    "assign_cohort_scope",
    "COHORT_MIN_SIZE",
    "PARENT_MIN_SIZE",
    "blended_percentile_rank",
    "blended_zscore",
    "clip",
    "exponential_decay",
    "mean_std",
    "percentile_rank",
    "percentile_rank_fraction",
    "shrinkage_lambda",
    "shrinkage_tier_weights",
    "winsorise",
    "zscore",
    "contiguous_weakening_streak",
    "latest_session_on_or_before",
    "normalise_calendar",
    "nth_prior_session",
    "prior_sessions",
    "sessions_between",
]
